title: "alog"
description: "A minimal blog powered by Jekyll"
baseurl: "/alog"
url: "https://gujiaxi.github.io"

theme: minima

# Minima skin: classic / solarized / solarized-dark / dark
minima:
  skin: classic

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-seo-tag
