title: "Alog"
description: "人工智能领域技术研究博客。"
baseurl: "/alog"
url: "https://gujiaxi.github.io"
author: "AI Research"

theme: minima

minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links: []

# MathJax
markdown: kramdown
kramdown:
  math_engine: mathjax

highlighter: rouge
permalink: /:year/:month/:day/:title/

show_excerpts: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-seo-tag
